### ISSUE TITLE
use newer embedded-redis fork

### ISSUE THREAD

**Issue by martin-mfg** [fizzgate/fizz-gateway-community#471]
Hi,
I see you are using the dependency [it.ozimov:embedded-redis](https://github.com/ozimov/embedded-redis) in several places. This project is not maintained anymore. But there are several forks available, so I would like to suggest migrating to one of those forks. Please see [codemonstur/embedded-redis](https://github.com/codemonstur/embedded-redis), [ponfee/embedded-redis](https://github.com/ponfee/embedded-redis), [simbahebinbo/embedded-redis](https://github.com/simbahebinbo/embedded-redis) and [signalapp/embedded-redis](https://github.com/signalapp/embedded-redis).

**Comment by hongqiaowei** [comment]
Because those forks not support windows (no windows executable in those forks)

**Comment by hongqiaowei** [comment]
Because those forks not support windows (no windows executable in those forks)

**Comment by hongqiaowei** [comment]
Thank you for your suggestion, but those forks not support windows. (no windows executable in those forks)

**Comment by martin-mfg** [comment]
Hi @hongqiaowei, [codemonstur/embedded-redis](https://github.com/codemonstur/embedded-redis) does actually support Windows. 🙂 It's listed [here](https://github.com/codemonstur/embedded-redis#redis-version) in the readme.
